# Generated by Django 6.0 on 2026-07-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedpackage',
            name='is_legacy',
        ),
    ]
